# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vw7E64lBGgjY7c2jyMC5qIo_iFUOKkt2
"""

import pandas as pd
import numpy as np

df = pd.read_csv('emails.csv')

df.head()

df.info()

df.describe()

x = df.drop(['Email No.' , 'Prediction'] , axis = 1)

y = df['Prediction']

from sklearn.preprocessing import MinMaxScaler
model = MinMaxScaler()
x = model.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)

from sklearn.neighbors import KNeighborsClassifier
Kmodel = KNeighborsClassifier(n_neighbors=8)
Kmodel.fit(x_train , y_train)

y_pred = Kmodel.predict(x_test)

from sklearn.metrics import ConfusionMatrixDisplay ,classification_report
matrix = ConfusionMatrixDisplay.from_predictions(y_test , y_pred)

print(classification_report(y_test , y_pred))

