# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-a_6fbtxcTL9Uc-QUEPAblEVR-85XziH
"""

import pandas as pd
import numpy as np

df = pd.read_csv('uber.csv')

df.info(

)

df.isna().sum()

df.dropna(inplace=True)

df.isna().sum()

df.drop(['Unnamed: 0' , 'key'] ,axis=1 ,inplace=True)

df.head()

df.info()

df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

df.info()

def treatOutliers(df,list):
  for col in list:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    upper = Q3 + (1.5 * IQR)
    lower = Q1 - (1.5 * IQR)
    np.clip(df[col],upper,lower,inplace = True)

treatOutliers(df,['pickup_longitude'])

sns.boxplot(df)

sns.heatmap(df.corr(),annot = True)

df.drop('pickup_datetime' ,axis=1 ,inplace= True)

x = df.drop('fare_amount',axis=1)
y = df['fare_amount']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('fare_amount',axis=1),df['fare_amount'],test_size=0.2)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))